# Generated by Django 4.1.5 on 2023-03-09 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploded_signs',
            name='sign',
            field=models.BinaryField(),
        ),
    ]
