# Generated by Django 4.1.5 on 2023-03-09 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_uploded_signs_sign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploded_signs',
            name='sign',
            field=models.ImageField(upload_to='signatures/'),
        ),
    ]
