# Generated by Django 5.0.4 on 2024-05-06 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_verify_sign'),
    ]

    operations = [
        migrations.AddField(
            model_name='verify_sign',
            name='pname',
            field=models.CharField(default=1, max_length=70),
            preserve_default=False,
        ),
    ]
