# Generated by Django 5.0.4 on 2024-05-07 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_verify_sign_pname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Uploded_signs',
        ),
    ]
